// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://jsaygzvybdeqgvovygms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "sb_publishable_DPQjOGeXrpLFF8NDlHheTw_bGgmuzRu";
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzYXlnenZ5YmRlcWd2b3Z5Z21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3Mjg4NDIsImV4cCI6MjA4ODMwNDg0Mn0.i8luKCRZPdAIK485unhXFNUSz1fyvJP7xPu3kUwKH0s";

// Use the anon key for client-side operations
const API_KEY = SUPABASE_ANON_KEY || SUPABASE_PUBLISHABLE_KEY;

if (!API_KEY) {
  console.error("No Supabase API key found! Check your .env file.");
}
if (!SUPABASE_URL) {
  console.error("No Supabase URL found! Check your .env file.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, API_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
  },
});
